version: '3.8'

services:
  web:
    build: .
    command: gunicorn myProject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: default_db
      POSTGRES_USER: cloud_user
      POSTGRES_PASSWORD: vN%rJ3w4d9au
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: default_db
      POSTGRES_USER: cloud_user
      POSTGRES_PASSWORD: vN%rJ3w4d9au
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
