# Generated by Django 4.2.2 on 2024-04-10 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news_app", "0007_tag_article_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecomment",
            name="dislikes",
            field=models.ManyToManyField(
                blank=True,
                related_name="disliked_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="articlecomment",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_comments", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
