# Generated by Django 4.2.2 on 2024-03-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0005_articlecomment_parent_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="articles_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
