# Generated by Django 4.2.2 on 2024-04-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0009_alter_articlecomment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlecomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="news_app.articlecomment",
            ),
        ),
    ]
