# Generated by Django 4.2.2 on 2024-04-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0010_alter_articlecomment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlecomment",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
