# Generated by Django 4.2 on 2024-05-13 08:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0012_comment_dislikes_comment_is_deleted_comment_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="content",
        ),
        migrations.RemoveField(
            model_name="article",
            name="image",
        ),
        migrations.CreateModel(
            name="ArticleContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("text", "Текст"), ("image", "Изображение")],
                        max_length=10,
                        verbose_name="Тип контента",
                    ),
                ),
                (
                    "text_content",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Текстовый контент"
                    ),
                ),
                (
                    "image_content",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="articles_images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_blocks",
                        to="news_app.article",
                    ),
                ),
            ],
        ),
    ]
