# Generated by Django 4.2 on 2024-05-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0013_remove_article_content_remove_article_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="content",
            field=models.TextField(default=1, verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="articles_images/",
                verbose_name="Изображение",
            ),
        ),
        migrations.DeleteModel(
            name="ArticleContentBlock",
        ),
    ]
