# Generated by Django 4.2 on 2024-05-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0016_remove_article_image_alter_article_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="articles_images/",
                verbose_name="Изображение",
            ),
        ),
    ]
