# Generated by Django 4.2 on 2024-05-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0017_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.DeleteModel(
            name="ArticleImage",
        ),
    ]
