# Generated by Django 4.2 on 2024-05-14 07:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0018_alter_article_content_delete_articleimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Описание"
            ),
        ),
    ]
