# Generated by Django 4.2 on 2024-05-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0020_alter_article_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(verbose_name="Описание"),
        ),
    ]
